# Generated by Django 3.0 on 2024-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachreg',
            name='document',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
